import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full bg-blue-pri antialiased`}
    >
      <body className="min-h-full max-w-360 min-w-93.75 mx-auto flex flex-col">
        {children}
      </body>
    </html>
  )
}
